server:
  port: 9009
spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: localhost
aliyun:
  sms:
    accessKeyId: LACI5FkGNRRKb1Rh5YgFuheB
    accessKeySecret: jlkYgz6OYv3m2CAugnHbfPwK5tfvCe
    template_code: SMS_184621468
    sign_name: 乐优商城
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true